language: ruby
rvm:
  - 2.5.0
services:
  - elasticsearch
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - sleep 10
script: 
  - export RAILS_ENV=test
  - bundle exec rake db:create db:schema:load db:test:prepare
  - bundle exec rspec spec/models
